POST localhost:8080/v1/auth/register
Content-Type: application/json

{
  "name": {
    "first": "Davi",
    "last": "Seagull"
  },
  "username": "daviseagull",
  "email": "davi.seagull@gmail.com",
  "password": "testeteste",
  "role": "APP_ADMIN"
}

###

POST localhost:8080/v1/auth/authenticate
Content-Type: application/json

{
  "username": "daviseagull",
  "password": "testeteste"
}


